### ISSUE TITLE
Hacktoberfest 2021! 🚀

### ISSUE THREAD

**Issue by abxhr** [abxhr/Open-DSA#1]
<p align="center">
<b>Hacktoberfest 2021 is finally here!!</b><br>
<i>Accepting contributions! </i>💖
</p>

Create a Pull Request, and add implementation of Data Structures and Algorithms (**only in CPP**), along with their documentation! 

## Guidelines:
- **Pull requests won't be accepted if unassigned**. So get assigned, before you start working on a pull request.
- Before you start working on this repository, make sure to tell us which Data Structure or Algorithm you will be implementing. Make sure to be specific on the concept (*eg:* `Insertion Sort`, `Doubly Linked List`, etc.)
- **Make sure to first check if the concept you want to work on is not yet implemented, or assigned.** 
- When working on a concept, make sure to implement all the possible manipulations for it (*eg*: for `Singly Linked List`, show the working of `inserting a node`, `deleting a node`, `searching for a node`, etc.). If this is not possible, implement the essential manipulations atleast.
- After you are done working on a concept, don't forget to add document it in the **3** documentation files:
  1. `Open-DSA/README.md`
  2. `Open-DSA/Algorithms` or `Open-DSA/Data-Structures` - according to concept implemented
  3. Specific `README.md` for a concept (*eg:* For implementation of `Binary Search Tree`, file created at `Open-DSA/Data-Structures/Trees/BinarySeachTree/README.md`)
- While adding documentation for a specific `README.md` for a concept, make sure to add information such as *Complexity*, *Applications*, *Possible Errors*, etc., according to what you feel might be essential information. (Check out [this](https://github.com/abxhr/Open-DSA/tree/main/Data%20Structures/Arrays) for an example)

## Assigned:
| Assignee | Concept | Complete |
|-----------|---------|---------|
| @UtkarshKislay | `Tree traversal` (Inorder, Preorder and Postorder) |  |
| @redhawk2002 | `Templates`, `Dynamic Stack` |  |
| @Gopal-Dahale | `DP` - (`knapsack`, `subset sum problem`, `equal sum partition`, `unbounded knapsack` and `rod cutting problems` |  |
| @pranju27 | `BFS` (using STL) |  |
| @AdityaVSM | `Left Shift Operation`, `Right Shift Operation` | ✅ |

**Comment by Dinesh765** [comment]
Can I work on this issue? I can add Searching and sorting algorithms.

**Comment by AdityaVSM** [comment]
I would like to contribute some arrays based algorithms like left/right shift etc.. Can you assign it to me?

**Comment by plavani0208** [comment]
Can i work on this? I can add linked lists Data structure and algorithms based on them.

**Comment by Divya333** [comment]
please assign this to me i will do sorting algorithm

**Comment by redhawk2002** [comment]
I would like to contribute on stack data structure. Can you assign it to me?

**Comment by pranju27** [comment]
Tysm for this. i would like to kickstart my open source contribution by implementing most efficient Quick sort algorithm. kindly assign it to me.

**Comment by UtkarshKislay** [comment]
I would like to contribute by implementing tree and graph data structure . Can you assign it to me?

**Comment by abxhr** [comment]
@Dinesh765 Sure! Could you be a little more specific to what concept in Searching or Sorting will you be implementing, so that I could assign you accordingly?

@AdityaVSM Thank you for taking your time to contributing to this repository! Could you tell the specific concept you will be implementing, so that I could assign you accordingly?

@plavani0208 Basic Linked Lists are already implemented ([here](https://github.com/abxhr/Open-DSA/tree/main/Data%20Structures/LinkedList)). Could you tell me what specifically you will be working on, so that I could assign it to you?

@Divya333 Sure! Could you tell me which Sorting Algorithm you want to work on specifically?

@redhawk2002 The `stack` data structure has already been implemented. You could maybe check it out [here](https://github.com/abxhr/Open-DSA/tree/main/Data%20Structures/Stacks), and maybe work on adding additional functionality to it. Let me know what you want to work on, so that I could assign you.

@pranju27 Thank you for taking your time to contributing to this repository! The `quick sort` algorithm has already been implemented [here](https://github.com/abxhr/Open-DSA/tree/main/Algorithms/Sorting/QuickSort). You could maybe work on implementing some other concept. Let me know so that I could assign it to you.

@UtkarshKislay Sure! Could you be a little more specific on which concept in `Trees` or `Graphs` you would like to work on (*eg*: `Binary Search Tree`), so that I could assign it to you?

**Comment by UtkarshKislay** [comment]
I can contribute in implementation of tree traversal  (Inorder, Preorder and Postorder).

**Comment by abxhr** [comment]
@UtkarshKislay Alright! Assigned it to you! 🚀

**Comment by redhawk2002** [comment]
@abxhr I can implement with some extras like using **template** for any data type and **dynamic stack** for getting freedom for the fix size of the stack

**Comment by abxhr** [comment]
@redhawk2002 Cool! Assigned it to you! 🚀

**Comment by Gopal-Dahale** [comment]
@abxhr I would like to work on dynamic programming algorithms (specifically knapsack, subset sum problem, equal sum partition), unbounded knapsack and rod cutting problems. It will be nice if you create a folder for dynamic programming so that I can contribute to it. 
Thank you

**Comment by abxhr** [comment]
@Gopal-Dahale Done! Assigned it to you 🚀

**Comment by pranju27** [comment]
i would like to implement BFS algo using STL and provide detailed documentation too.

**Comment by AdityaVSM** [comment]
> @Dinesh765 Sure! Could you be a little more specific to what concept in Searching or Sorting will you be implementing, so that I could assign you accordingly?
> 
> @AdityaVSM Thank you for taking your time to contributing to this repository! Could you tell the specific concept you will be implementing, so that I could assign you accordingly?
> 
> @plavani0208 Basic Linked Lists are already implemented ([here](https://github.com/abxhr/Open-DSA/tree/main/Data%20Structures/LinkedList)). Could you tell me what specifically you will be working on, so that I could assign it to you?
> 
> @Divya333 Sure! Could you tell me which Sorting Algorithm you want to work on specifically?
> 
> @redhawk2002 The `stack` data structure has already been implemented. You could maybe check it out [here](https://github.com/abxhr/Open-DSA/tree/main/Data%20Structures/Stacks), and maybe work on adding additional functionality to it. Let me know what you want to work on, so that I could assign you.
> 
> @pranju27 Thank you for taking your time to contributing to this repository! The `quick sort` algorithm has already been implemented [here](https://github.com/abxhr/Open-DSA/tree/main/Algorithms/Sorting/QuickSort). You could maybe work on implementing some other concept. Let me know so that I could assign it to you.
> 
> @UtkarshKislay Sure! Could you be a little more specific on which concept in `Trees` or `Graphs` you would like to work on (_eg_: `Binary Search Tree`), so that I could assign it to you?

I would like to add some array-based programs like left shift operation, right shift operation, etc.. also I want to add some common recursive algorithms like rope cutting algorithm, tower of Hanoi, substrings, subset-sum etc..

**Comment by abxhr** [comment]
@pranju27 Cool! Assigned it to you! 🚀

**Comment by abxhr** [comment]
@Divya333 `Bubble sort` algorithm has already been implemented [here](https://github.com/abxhr/Open-DSA/tree/main/Algorithms/Sorting/BubbleSort). Let me know if you would like to work on anything else.

**Comment by abxhr** [comment]
@AdityaVSM Cool! I'm only assigning you for `Left Shift Operation` and `Right Shift Operation`. Once you are done merging the code for it, you can take up more concepts 🚀

**Comment by AdityaVSM** [comment]
@abxhr Can you check PR #5 and let me know if any changes are required.

**Comment by Divya333** [comment]
i would like to work on quick sort

**Comment by abxhr** [comment]
@Om12Dahale Alright! Assigned it to you! 🚀

**Comment by abxhr** [comment]
@Divya333 The `quick sort` algorithms has been implemented as well. Please refer to the repository, to check which has not been implemented yet.

**Comment by radha919** [comment]
i would like to work in insertion sort in c++.

**Comment by radha919** [comment]
@abxhr could you please assign it to  me?

**Comment by abxhr** [comment]
@radha919 `Insertion Sort` has already been implemented

**Comment by radha919** [comment]
@abxhr i would like to contribute in selection sort.

**Comment by abxhr** [comment]
@radha919 `Selection Sort` has been implemented as well. Please refer to the repository.

**Comment by Abhi-1301** [comment]
Please assign me graph algorithms, I would like to contribute

**Comment by abxhr** [comment]
@Abhi-1301 Cool! Assigned it to you! 🚀

**Comment by radha919** [comment]
@abxhr can i contribute in linked list topic?

**Comment by abxhr** [comment]
@radha919 That is implemented as well. Please refer to the repository to check what is implemented and what is not.

**Comment by radha919** [comment]
@abxhr  could you please assign me any dsa topic?

**Comment by radha919** [comment]
yes i can @abxhr

**Comment by abxhr** [comment]
@radha919 Cool! You may work on it! Assigned it to you 🚀

**Comment by SauravRaj8** [comment]
Hello, @abxhr I would like to contribute programs on dp related problems:-
Longest palindromic substring
Longest arithmetic subsequence
Matix chain multiplication
Maximum product subarray

Can you assign me these problems?

**Comment by abxhr** [comment]
@CoderShubham2000 Sure! Assigned it to you 🚀

**Comment by abxhr** [comment]
@SauravRaj8 Cool! Assigned it to you! 🚀

**Comment by AdityaVSM** [comment]
@abxhr can you check PR #14

**Comment by CoderShubham2000** [comment]
> @CoderShubham2000 Sure! Assigned it to you 🚀

@abxhr Can you check PR #15

**Comment by Abhi-1301** [comment]
@abxhr can you please check PR #13

**Comment by radha919** [comment]
@abxhr  can you please check me PR.

**Comment by 20ritesh** [comment]
I would like to contribute on linear and binary search.

**Comment by kajal1801** [comment]
Can I add a new topic - Double dimensional Arrays?

**Comment by swarnajha** [comment]
Can I add armstrong number or some string problems like  palindrome string ,anagram in dynamic programming ? @abxhr

**Comment by swarnajha** [comment]
Can I add a program for n’th node from the end of a Linked List ?

**Comment by ashutosh321607** [comment]
@abxhr  Can I add a program for the kth largest element in an array using heap?

**Comment by atmish01** [comment]
@abxhr Please check PR #26 and let me know if any changes are required

**Comment by abxhr** [comment]
@ashutosh321607 Yess! Go ahead! 
@sejalsingh417 Cool! You can work on that!
